### ISSUE TITLE
no support for latest version of tornado

### ISSUE THREAD

**Issue by twobraids** [mozilla-iot/webthing-python#46]
Importing `webthing` fails:

```
(py37) $ pip install webthing
Collecting webthing
  Using cached https://files.pythonhosted.org/packages/bf/46/b8460dd86abfd59d181697ede692797edffa79df262485717ed33d0e4d3d/webthing-0.11.1-py3-none-any.whl
Requirement already satisfied: jsonschema in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from webthing) (3.0.1)
Requirement already satisfied: netifaces in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from webthing) (0.10.9)
Requirement already satisfied: pyee in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from webthing) (5.0.0)
Requirement already satisfied: tornado in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from webthing) (6.0.1)
Requirement already satisfied: zeroconf in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from webthing) (0.21.3)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from jsonschema->webthing) (0.14.11)
Requirement already satisfied: six>=1.11.0 in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from jsonschema->webthing) (1.12.0)
Requirement already satisfied: setuptools in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from jsonschema->webthing) (40.6.2)
Requirement already satisfied: attrs>=17.4.0 in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from jsonschema->webthing) (19.1.0)
Requirement already satisfied: ifaddr in /home/lars/project/lars_iot/py37/lib/python3.7/site-packages (from zeroconf->webthing) (0.1.6)
Installing collected packages: webthing
Successfully installed webthing-0.11.1
(py37) $ python
Python 3.7.2 (default, Feb 25 2019, 16:59:29) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import webthing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lars/project/lars_iot/py37/lib/python3.7/site-packages/webthing/__init__.py", line 7, in <module>
    from .server import MultipleThings, SingleThing, WebThingServer
  File "/home/lars/project/lars_iot/py37/lib/python3.7/site-packages/webthing/server.py", line 152, in <module>
    class ThingHandler(tornado.websocket.WebSocketHandler):
  File "/home/lars/project/lars_iot/py37/lib/python3.7/site-packages/webthing/server.py", line 191, in ThingHandler
    @tornado.web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
>>> 
```

**Comment by twobraids** [comment]
The `requirements.txt` file for `webthing` specifies `tornado>=5.1.0`.  Unfortunately, Version 6 of `tornado` was released on March 1, 2019 and it has breaking changes.  Likely this could be resolved by either pinning the `webthing` to 5.1.0 or adjusting the code to work with `tornado 6.0.1`.  Unfortunately, I cannot get the former to work and haven't had the chance to try the latter.

The `tornado 6.0.0` release notes (https://www.tornadoweb.org/en/stable/releases/v6.0.0.html) documents the removal of the `asynchronous` decorator, but makes no suggestion as to how to proceed without it.
